import { notFound } from 'next/navigation'
import { ContentCard } from '@/components/listings/content-card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ArrowLeft, RefreshCw } from 'lucide-react'
import Link from 'next/link'
import { regenerateContent } from '@/lib/actions/listings'
import { auth } from '@/auth'
import { prisma } from '@/lib/prisma'

const CARDS = [
  {
    key: 'facebook' as const,
    platform: 'Facebook',
    accentColor: 'border-l-blue-500',
    icon: <span className="text-blue-600 font-bold text-xs w-4 text-center">f</span>,
  },
  {
    key: 'instagram' as const,
    platform: 'Instagram',
    accentColor: 'border-l-pink-500',
    icon: <span className="text-pink-500 font-bold text-xs w-4 text-center">IG</span>,
  },
  {
    key: 'linkedin' as const,
    platform: 'LinkedIn',
    accentColor: 'border-l-sky-500',
    icon: <span className="text-sky-600 font-bold text-xs w-4 text-center">in</span>,
  },
  {
    key: 'newsletter' as const,
    platform: 'Newsletter',
    accentColor: 'border-l-indigo-500',
    icon: <span className="text-indigo-500 text-xs w-4 text-center">✉</span>,
  },
  {
    key: 'groupchat' as const,
    platform: 'Realtor Groupchat',
    accentColor: 'border-l-slate-400',
    icon: <span className="text-slate-500 text-xs w-4 text-center">💬</span>,
  },
] as const

export default async function ListingPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params

  const session = await auth()
  const userId = session?.user?.id
  if (!userId) notFound()

  let listing
  try {
    listing = await prisma.listing.findFirst({
      where: { id, userId },
      include: { generatedContent: true },
    })
  } catch (err) {
    console.error('[ListingPage] prisma query failed:', err)
    throw err
  }

  if (!listing) notFound()

  const content = listing.generatedContent

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-start gap-3">
        <Button variant="ghost" size="icon" asChild className="text-slate-400 mt-1">
          <Link href="/listings">
            <ArrowLeft className="w-4 h-4" />
          </Link>
        </Button>
        <div className="flex-1">
          <h1 className="text-xl font-bold text-slate-900">{listing.address}</h1>
          <div className="flex flex-wrap items-center gap-2 mt-1">
            {listing.city && listing.state && (
              <span className="text-sm text-slate-500">
                {listing.city}, {listing.state}
              </span>
            )}
            {listing.listPrice && (
              <Badge variant="outline" className="border-blue-200 text-blue-700">
                ${listing.listPrice.toLocaleString()}
              </Badge>
            )}
            {listing.beds && (
              <span className="text-sm text-slate-500">{listing.beds}bd</span>
            )}
            {listing.baths && (
              <span className="text-sm text-slate-500">{listing.baths}ba</span>
            )}
            {listing.sqft && (
              <span className="text-sm text-slate-500">{listing.sqft.toLocaleString()} sqft</span>
            )}
          </div>
        </div>
        <form
          action={async () => {
            'use server'
            await regenerateContent(id)
          }}
        >
          <Button
            variant="outline"
            size="sm"
            className="border-blue-200 text-blue-600 hover:bg-blue-50"
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Regenerate All
          </Button>
        </form>
      </div>

      {/* Content cards */}
      {content ? (
        <div className="space-y-4">
          {CARDS.map(({ key, platform, accentColor, icon }) => (
            <ContentCard
              key={key}
              platform={platform}
              content={content[key]}
              accentColor={accentColor}
              icon={icon}
            />
          ))}
          <p className="text-xs text-slate-400 text-center">
            Generated by {content.provider}
          </p>
        </div>
      ) : (
        <div className="text-center py-12 text-slate-500">
          No content generated yet.
        </div>
      )}
    </div>
  )
}
