import { notFound } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { auth } from '@/auth'
import { prisma } from '@/lib/prisma'
import { RegenerateButton } from '@/components/listings/regenerate-button'
import { MockPostShell } from '@/components/listings/platform-mocks/mock-post-shell'
import { FacebookPost } from '@/components/listings/platform-mocks/facebook-post'
import { InstagramPost } from '@/components/listings/platform-mocks/instagram-post'
import { LinkedInPost } from '@/components/listings/platform-mocks/linkedin-post'
import { NewsletterBlock } from '@/components/listings/platform-mocks/newsletter-block'
import { GroupchatBubble } from '@/components/listings/platform-mocks/groupchat-bubble'

function getInitials(name: string | null | undefined): string {
  if (!name) return 'RE'
  return name
    .split(' ')
    .map(n => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
}

export default async function ListingPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = await params

  const session = await auth()
  const userId = session?.user?.id
  if (!userId) notFound()

  let listing
  try {
    listing = await prisma.listing.findFirst({
      where: { id, userId },
      include: { generatedContent: true },
    })
  } catch (err) {
    console.error('[ListingPage] prisma query failed:', err)
    throw err
  }

  if (!listing) notFound()

  const content = listing.generatedContent
  const userName = session?.user?.name ?? 'Your Name'
  const userInitials = getInitials(session?.user?.name)

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-start gap-3">
        <Button variant="ghost" size="icon" asChild className="text-slate-400 mt-1">
          <Link href="/listings">
            <ArrowLeft className="w-4 h-4" />
          </Link>
        </Button>
        <div className="flex-1">
          <h1 className="text-xl font-bold text-slate-900">{listing.address}</h1>
          <div className="flex flex-wrap items-center gap-2 mt-1">
            {listing.city && listing.state && (
              <span className="text-sm text-slate-500">
                {listing.city}, {listing.state}
              </span>
            )}
            {listing.listPrice && (
              <Badge variant="outline" className="border-blue-200 text-blue-700">
                ${listing.listPrice.toLocaleString()}
              </Badge>
            )}
            {listing.beds && (
              <span className="text-sm text-slate-500">{listing.beds}bd</span>
            )}
            {listing.baths && (
              <span className="text-sm text-slate-500">{listing.baths}ba</span>
            )}
            {listing.sqft && (
              <span className="text-sm text-slate-500">{listing.sqft.toLocaleString()} sqft</span>
            )}
          </div>
        </div>
        <RegenerateButton listingId={id} />
      </div>

      {/* Platform mocks */}
      {content ? (
        <div className="space-y-8">
          <MockPostShell content={content.facebook} label="Facebook">
            {(text) => <FacebookPost content={text} userName={userName} userInitials={userInitials} />}
          </MockPostShell>

          <MockPostShell content={content.instagram} label="Instagram">
            {(text) => <InstagramPost content={text} userName={userName} userInitials={userInitials} />}
          </MockPostShell>

          <MockPostShell content={content.linkedin} label="LinkedIn">
            {(text) => <LinkedInPost content={text} userName={userName} userInitials={userInitials} />}
          </MockPostShell>

          <MockPostShell content={content.newsletter} label="Newsletter">
            {(text) => <NewsletterBlock content={text} userName={userName} />}
          </MockPostShell>

          <MockPostShell content={content.groupchat} label="Realtor Groupchat">
            {(text) => <GroupchatBubble content={text} userName={userName} userInitials={userInitials} />}
          </MockPostShell>

          <p className="text-xs text-slate-400 text-center pb-4">
            Generated by {content.provider}
          </p>
        </div>
      ) : (
        <div className="text-center py-12 text-slate-500">
          No content generated yet.
        </div>
      )}
    </div>
  )
}
